<?php

namespace ContainerEJZPbSs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pfp9WASService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pfp9WAS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pfp9WAS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', '.errored.Gm8GyeN', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfilSortieController::addProfilSortie()": the $manager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.nFCMTSc', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfilSortieController::addProfilSortie()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'serializer' => ['privates', '.errored.pirKeRE', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfilSortieController::addProfilSortie()": the $serializer argument is type-hinted with the non-existent class or interface: "App\\Controller\\SerializerInterface". Did you forget to add a use statement?'],
            'validator' => ['privates', '.errored.G3FEEBK', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfilSortieController::addProfilSortie()": the $validator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ValidatorInterface". Did you forget to add a use statement?'],
        ], [
            'manager' => '?',
            'request' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
