<?php

namespace ContainerEJZPbSs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_G3FEEBKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.G3FEEBK' shared service.
     *
     * @return \App\Controller\ValidatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ProfilSortieController::addProfilSortie()": the $validator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ValidatorInterface". Did you forget to add a use statement?');
    }
}
