<?php

namespace ContainerLaGQyMX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PjyjTWgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pjyjTWg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pjyjTWg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'method' => ['privates', 'App\\Main', 'getMainService', true],
            'repo' => ['privates', 'App\\Repository\\ProfilSortieRepository', 'getProfilSortieRepositoryService', true],
        ], [
            'method' => 'App\\Main',
            'repo' => 'App\\Repository\\ProfilSortieRepository',
        ]);
    }
}
