<?php

namespace ContainerPUBIALL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P7WIa81Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p7WIa81' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p7WIa81'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'denormalizer' => ['services', 'serializer', 'getSerializerService', false],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\GroupeCompetenceRepository', 'getGroupeCompetenceRepositoryService', true],
            'repo2' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'denormalizer' => '?',
            'manager' => '?',
            'repo' => 'App\\Repository\\GroupeCompetenceRepository',
            'repo2' => 'App\\Repository\\CompetenceRepository',
            'serializer' => '?',
        ]);
    }
}
