<?php

namespace ContainerXFscWft;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SoTXMSrService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.soTXMSr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.soTXMSr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'serve' => ['privates', 'App\\Service\\MyService', 'getMyServiceService', true],
        ], [
            'manager' => '?',
            'serializer' => '?',
            'serve' => 'App\\Service\\MyService',
        ]);
    }
}
