<?php

namespace ContainerMxxHdQN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Main' shared autowired service.
     *
     * @return \App\Main
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Main.php';

        return $container->privates['App\\Main'] = new \App\Main(($container->services['serializer'] ?? $container->getSerializerService()));
    }
}
