<?php

namespace ContainerNbGDcP6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YqoYghkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.yqoYghk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yqoYghk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CompetenceController::addCompetence' => ['privates', '.service_locator.XJm310N', 'get_ServiceLocator_XJm310NService', true],
            'App\\Controller\\GroupeCompetenceController::addGrpCompetence' => ['privates', '.service_locator.WzYPJck', 'get_ServiceLocator_WzYPJckService', true],
            'App\\Controller\\ProfilController::addProfil' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\USerController::addUser' => ['privates', '.service_locator.xPCyVuZ', 'get_ServiceLocator_XPCyVuZService', true],
            'App\\Controller\\USerController::updateUser' => ['privates', '.service_locator.soTXMSr', 'get_ServiceLocator_SoTXMSrService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CompetenceController:addCompetence' => ['privates', '.service_locator.XJm310N', 'get_ServiceLocator_XJm310NService', true],
            'App\\Controller\\GroupeCompetenceController:addGrpCompetence' => ['privates', '.service_locator.WzYPJck', 'get_ServiceLocator_WzYPJckService', true],
            'App\\Controller\\ProfilController:addProfil' => ['privates', '.service_locator.19ps0qC', 'get_ServiceLocator_19ps0qCService', true],
            'App\\Controller\\USerController:addUser' => ['privates', '.service_locator.xPCyVuZ', 'get_ServiceLocator_XPCyVuZService', true],
            'App\\Controller\\USerController:updateUser' => ['privates', '.service_locator.soTXMSr', 'get_ServiceLocator_SoTXMSrService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CompetenceController::addCompetence' => '?',
            'App\\Controller\\GroupeCompetenceController::addGrpCompetence' => '?',
            'App\\Controller\\ProfilController::addProfil' => '?',
            'App\\Controller\\USerController::addUser' => '?',
            'App\\Controller\\USerController::updateUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CompetenceController:addCompetence' => '?',
            'App\\Controller\\GroupeCompetenceController:addGrpCompetence' => '?',
            'App\\Controller\\ProfilController:addProfil' => '?',
            'App\\Controller\\USerController:addUser' => '?',
            'App\\Controller\\USerController:updateUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
