<?php

namespace ContainerNbGDcP6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Fixtures_LoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures.loader' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ProfilSortieFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/Profilfixtures.php';

        $container->privates['doctrine.fixtures.loader'] = $instance = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $instance->addFixtures([0 => ['fixture' => ($container->privates['App\\DataFixtures\\Adminfixtures'] ?? $container->load('getAdminfixturesService')), 'groups' => []], 1 => ['fixture' => ($container->privates['App\\DataFixtures\\Apprenantfixtures'] ?? $container->load('getApprenantfixturesService')), 'groups' => []], 2 => ['fixture' => ($container->privates['App\\DataFixtures\\Cmfixtures'] ?? $container->load('getCmfixturesService')), 'groups' => []], 3 => ['fixture' => ($container->privates['App\\DataFixtures\\Formateurfixtures'] ?? $container->load('getFormateurfixturesService')), 'groups' => []], 4 => ['fixture' => ($container->privates['App\\DataFixtures\\ProfilSortieFixtures'] ?? ($container->privates['App\\DataFixtures\\ProfilSortieFixtures'] = new \App\DataFixtures\ProfilSortieFixtures())), 'groups' => []], 5 => ['fixture' => ($container->privates['App\\DataFixtures\\Profilfixtures'] ?? ($container->privates['App\\DataFixtures\\Profilfixtures'] = new \App\DataFixtures\Profilfixtures())), 'groups' => []]]);

        return $instance;
    }
}
