<?php

namespace ContainerNbGDcP6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilVoterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\Voter\ProfilVoter' shared autowired service.
     *
     * @return \App\Security\Voter\ProfilVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/ProfilVoter.php';

        return $container->privates['App\\Security\\Voter\\ProfilVoter'] = new \App\Security\Voter\ProfilVoter();
    }
}
