<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLaGQyMX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLaGQyMX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLaGQyMX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLaGQyMX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLaGQyMX\App_KernelDevDebugContainer([
    'container.build_hash' => 'LaGQyMX',
    'container.build_id' => '2f55d3b1',
    'container.build_time' => 1615777625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLaGQyMX');
