<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxxHdQN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxxHdQN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxxHdQN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxxHdQN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxxHdQN\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxxHdQN',
    'container.build_id' => '1ad5835f',
    'container.build_time' => 1613490104,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxxHdQN');
