<?php

namespace ContainerXfv3Mew;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ANX5z1NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aNX5z1N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aNX5z1N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'denormalizer' => ['services', 'serializer', 'getSerializerService', false],
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
            'serve' => ['privates', 'App\\Service\\MyService', 'getMyServiceService', true],
        ], [
            'denormalizer' => '?',
            'encoder' => '?',
            'manager' => '?',
            'repo' => 'App\\Repository\\UserRepository',
            'serializer' => '?',
            'serve' => 'App\\Service\\MyService',
        ]);
    }
}
