<?php

namespace ContainerXfv3Mew;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MyService' shared autowired service.
     *
     * @return \App\Service\MyService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MyService.php';

        return $container->privates['App\\Service\\MyService'] = new \App\Service\MyService();
    }
}
